"""Add UserPushToken

Revision ID: e6b28b19d844
Revises: 0002_security_master_fields
Create Date: 2026-04-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b28b19d844'
down_revision: Union[str, None] = '0005_add_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expo_push_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expo_push_token'),
    schema='consensus_app'
    )
    op.create_index('ix_user_push_tokens_user_id', 'user_push_tokens', ['user_id'], unique=False, schema='consensus_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_push_tokens_user_id', table_name='user_push_tokens', schema='consensus_app')
    op.drop_table('user_push_tokens', schema='consensus_app')
    # ### end Alembic commands ###
